name: app

type: php:7.4

runtime:
    extensions:
        - pdo_pgsql
        - apcu
        - mbstring
        - sodium
        - ctype
        - iconv

variables:
    php:
    # uncomment on PHP 7.4+, needs Symfony 4.4.14+, 5.1.6+, or 5.2+
    #opcache.preload: /app/src/.preload.php
    php-ext: redis:5.3.1

build:
    flavor: none

relationships:
    database: "db:postgresql"
    redis: rediscache:redis

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

disk: 512

mounts:
    "/var": { source: local, source_path: var }
    "/public/uploads": { source: local, source_path: uploads}

hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)

        (>&2 symfony-build)

    deploy: |
        set -x -e

        (>&2 symfony-deploy)
